[project]
authors = ["Paul Link <paullink65@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "recursive_cli_search"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytest = ">=8.4.1,<9"
black = ">=25.1.0,<26"
pre-commit = ">=4.2.0,<5"
click = ">=8.2.1,<9"
anytree = ">=2.13.0,<3"

[pypi-dependencies]
recursive_cli_search = { path = ".", editable = true }
